name: stack-sample-project
version: '0.0.0'
category: template
synopsis: sample stack project that works as a fully annotated project template
description: >
    This project aims to provide a stack project that works as a template for
    many common use cases, including sample code for basic things.
author: Thomas Peiselt
github: dispanser/stack-sample-project
license: MIT

ghc-options: -Wall
dependencies:
  - base >= 4.8.0 && <5

library:
  source-dirs: src
  dependencies:
    - containers

tests:
  spec:
    source-dirs: spec
    main: Spec.hs
    dependencies:
      - stack-sample-project
      - hspec
  tasty:
    source-dirs: tasty
    main: TastyTests.hs
    dependencies:
      - stack-sample-project
      - hspec
      - tasty
      - tasty-hunit
      - tasty-hspec

benchmarks:
  sample-benchmark-criterion:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
    dependencies:
      - stack-sample-project
      - criterion
